server:
  port: 8880
spring:
  application:
    name: peer-service
eureka:
  instance:
    appname: peer-service
swagger:
  title: Message API
  description: Message API that return a message
  include: /api/.*

---
spring:
  profiles: vcloud
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: azure
server:
  port: 8882
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka